### ISSUE TITLE
Proposal: Move wiki of Eta under a repo

### ISSUE THREAD

**Issue by psibi** [typelead/eta-proposals#2]
Probably under the already existing docs folder in the eta repo ?

Or should we create a new one ?

The wiki seems to be already bit-rotten. It still refers to Eta as ghcvm.

Also most of the points of this article is valid: http://www.yesodweb.com/blog/2015/08/thoughts-on-documentation

**Comment by rahulmutt** [comment]
Reading that blog article is what caused me to shift the Eta documentations to the `docs/` subfolder in the main repo. I have just deleted the wiki - most of the information was out of date and more up-to-date information can be found in the docs.
